services:
  backend:
    build: .
    container_name: relink-backend
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./sql_app.db:/app/sql_app.db
  frontend:
    build: ./frontend
    container_name: relink-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
       - VITE_API_URL=http://localhost:8000/api/v1
    stdin_open: true
    tty: true